db-uri = "postgresql://postgres:postgres@172.18.0.5:5432/postgres"
db-schemas = "easylegal"
db-anon-role = "postgrest_anonymous"
db-extra-search-path = "public"
server-port = 3001
server-host = "0.0.0.0"
jwt-secret = "***REDACTED-JWT-SECRET***"
secret-is-base64 = false
