db-uri = "postgresql://postgres:postgres@172.18.0.5:5432/postgres"
db-schemas = "easylegal"
db-anon-role = "postgrest_anonymous"
db-extra-search-path = "public"
server-port = 3001
server-host = "0.0.0.0"
jwt-secret = "9012f916ba100fe8949e530f1f4eb5f088cacdaf128189486efa4116b4813ece"
secret-is-base64 = false
