/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "oxblood-hover": "#7A0101",
        "on-secondary-fixed": "#191c21",
        "oxblood-soft": "#FEF2F2",
        "background": "#f8f9fa",
        "surface-container-low": "#f3f4f5",
        "on-tertiary-fixed": "#002109",
        "text-muted": "#6B7280",
        "inverse-on-surface": "#f0f1f2",
        "surface": "#f8f9fa",
        "surface-variant": "#e1e3e4",
        "surface-tint": "#b82116",
        "on-secondary": "#ffffff",
        "primary": "#6f0000",
        "text-body": "#0F172A",
        "secondary-fixed-dim": "#c4c6cd",
        "surface-bright": "#f8f9fa",
        "secondary": "#5c5e64",
        "on-primary-fixed-variant": "#930001",
        "border-base": "#E5E7EB",
        "primary-container": "#990202",
        "secondary-fixed": "#e1e2e9",
        "on-background": "#191c1d",
        "error": "#DC2626",
        "inverse-primary": "#ffb4a8",
        "on-surface": "#191c1d",
        "warning": "#D97706",
        "on-secondary-fixed-variant": "#44474c",
        "on-tertiary-fixed-variant": "#005322",
        "success": "#059669",
        "error-container": "#ffdad6",
        "on-surface-variant": "#5b403c",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#ffb4a8",
        "surface-container-highest": "#e1e3e4",
        "inverse-surface": "#2e3132",
        "on-primary-container": "#ffa193",
        "tertiary-container": "#005624",
        "text-headline": "#111827",
        "tertiary": "#003c17",
        "secondary-container": "#dedfe6",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#410000",
        "outline-variant": "#e4beb8",
        "canvas-white": "#FFFFFF",
        "tertiary-fixed-dim": "#3de273",
        "surface-dim": "#d9dadb",
        "outline": "#8f706b",
        "on-tertiary-container": "#27d467",
        "on-error": "#ffffff",
        "surface-container": "#edeeef",
        "surface-container-high": "#e7e8e9",
        "on-secondary-container": "#606369",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#ffdad5",
        "tertiary-fixed": "#66ff8e"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "card-padding": "20px",
        "unit": "4px",
        "sidebar-width": "260px",
        "section-gap": "32px",
        "header-height": "64px",
        "gutter": "24px"
      },
      fontFamily: {
        "section-title": ["DM Sans"],
        "label-caps": ["JetBrains Mono"],
        "stat-metric": ["DM Sans"],
        "headline-md": ["DM Sans"],
        "body-bold": ["Inter"],
        "display-lg": ["DM Sans"],
        "table-header": ["Inter"],
        "body-base": ["Inter"]
      },
      fontSize: {
        "section-title": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "600" }],
        "stat-metric": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-bold": ["14px", { lineHeight: "22px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "table-header": ["12px", { lineHeight: "16px", letterSpacing: "0.03em", fontWeight: "700" }],
        "body-base": ["14px", { lineHeight: "22px", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
